--------------------------------------------------------
--  File created - Thursday-May-09-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SBIT2J_CART
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SBIT2J_CART" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CART_PRODID" VARCHAR2(10 BYTE), 
	"CART_PRODNAME" VARCHAR2(50 BYTE), 
	"CART_PRICE" NUMBER(20,2), 
	"CART_SIZE" VARCHAR2(20 BYTE), 
	"CART_QTY" NUMBER(38,0), 
	"CART_TOTAL" NUMBER(20,2), 
	"CART_PRODIMAGE" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 1, 
	"USERNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SBIT2J_CART
SET DEFINE OFF;
Insert into SYSTEM.SBIT2J_CART (ID,CART_PRODID,CART_PRODNAME,CART_PRICE,CART_SIZE,CART_QTY,CART_TOTAL,CART_PRODIMAGE,STATUS,USERNAME) values ('1','1003','Red Jacket',599,'Small',1,599,'WINDB3.png','0','almelon2');
--------------------------------------------------------
--  DDL for Index SBIT2J_CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SBIT2J_CART_PK" ON "SYSTEM"."SBIT2J_CART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SBIT2J_CART
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SBIT2J_CART" ADD CONSTRAINT "SBIT2J_CART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SBIT2J_CART" MODIFY ("ID" NOT NULL ENABLE);
